version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "cloud_netology"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "bestuser"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  restapp:
    image: 'restapp:latest'
    build:
      context: .
    container_name: restapp
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/cloud_netology?&useSSL=false&amp;serverTimezone=UTC
    ports:
      - "5555:5555"
  front:
    image: "frontcloudstorage:latest"
    ports:
      - "8080:8080"